server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APP_NAME:user-server}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/ticketing_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        show_sql: ${HIBERNATE_SHOW_SQL:false}
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
    open-in-view: ${SPRING_OPEN_IN_VIEW:false}

logging:
  level:
    org.hibernate.SQL: ${LOG_SQL_LEVEL:info}
    com.user: ${LOG_APP_LEVEL:info}

