server:
  port: 8080
spring:
  application:
    name: ticketing-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticketing_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: hwilee2529*
  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
    # MongoDB 설정 추가
    mongodb:
      uri: mongodb://localhost:27017/ticketing_logs
      auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  # Kafka 설정 추가
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ticketing-service
      auto-offset-reset: earliest # 토픽의 가장 처음부터 읽기 , latest (기본값): 가장 최근 메시지부터 읽기 (이전 메시지는 무시)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.ticketing.seat.event
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    org.hibernate.SQL: debug
    com.ticketing: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug
    org.springframework.kafka: info


