server:
  port: 8080
spring:
  application:
    name: ticketing-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticketing_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssafy
  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
    # MongoDB 설정 추가
    mongodb:
      uri: mongodb://localhost:27017/ticketing_logs
      auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  # Kafka 설정 추가
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.jackson.date-format: yyyy-MM-dd HH:mm:ss

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: com.ticketing.seat.event

    # KafkaListener의 수동 커밋 설정.
    listener:
      ack-mode: MANUAL_IMMEDIATE

  # 동시에 진행되는 스케줄링을 위해,
  # 병렬적으로 돌아갈 수 있는 스레드 개수 증가
  task:
    scheduling:
      pool:
        size: 4

logging:
  level:
    org.hibernate.SQL: debug
    com.ticketing: info
    org.springframework.data.mongodb.core.MongoTemplate: debug
    org.springframework.kafka: info

#Kafka 설정
app:
  kafka:
    # 기본 Kafka 연결 포트
    bootstrap-servers: localhost:9092

    # kafka Bean 기본 생성 여부
    admin:
      auto-create: true
      client-id: kafka-admin

    # Kafka Topic 별 partition, replica 개수 지정
    topics:
      queue:
        name: user-log
        partitions: 3
        replicas: 1

      captcha:
        name: captcha-log
        partitions: 3
        replicas : 1

# Actuator EndPoint 관리
management:
  endpoints:
    web:
      exposure:
        include: "*"   # 모든 엔드포인트 활성화
  endpoint:
    health:
      show-details: always  # health 세부 정보 표시

captcha:
  address: ${CAPTCHA_ADDRESS:http://localhost:8080/api/v1.0/captcha/}
  timeout: ${CAPTCHA_TIMEOUT:5000}

