name: Frontend CI/CD

on:
  push:
    branches:
      - dev
    paths:
      - 'Frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-dev:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      service_name: frontend
      service_path: Frontend
      docker_image: kkaebu/tickget-frontend
      environment: dev
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}
